"""Common Australian grocery ingredients seed data."""

SEED_INGREDIENTS = [
    # --- Meat ---
    {"name": "Chicken Breast", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 3},
    {"name": "Chicken Thigh", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 3},
    {"name": "Chicken Drumstick", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 3},
    {"name": "Beef Mince", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 2},
    {"name": "Beef Rump Steak", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 3},
    {"name": "Beef Chuck Steak", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 3},
    {"name": "Lamb Cutlets", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 3},
    {"name": "Lamb Mince", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 2},
    {"name": "Pork Mince", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 2},
    {"name": "Pork Loin Chops", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 3},
    {"name": "Bacon Rashers", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 7},
    {"name": "Beef Sausages", "category": "meat", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 3},
    # --- Seafood ---
    {"name": "Salmon Fillet", "category": "seafood", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 2},
    {"name": "Barramundi Fillet", "category": "seafood", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 2},
    {"name": "Prawns", "category": "seafood", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 2},
    {"name": "Tuna (Canned)", "category": "seafood", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 730},
    # --- Produce (Vegetables) ---
    {"name": "Onion", "category": "produce", "default_unit": "units", "default_storage": "pantry", "typical_shelf_life_days": 30},
    {"name": "Garlic", "category": "produce", "default_unit": "units", "default_storage": "pantry", "typical_shelf_life_days": 21},
    {"name": "Ginger", "category": "produce", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 21},
    {"name": "Carrot", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 14},
    {"name": "Potato", "category": "produce", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 21},
    {"name": "Sweet Potato", "category": "produce", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 14},
    {"name": "Broccoli", "category": "produce", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 5},
    {"name": "Capsicum", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 7},
    {"name": "Zucchini", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 7},
    {"name": "Mushrooms", "category": "produce", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 5},
    {"name": "Spinach", "category": "produce", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 5},
    {"name": "Tomato", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 7},
    {"name": "Lettuce", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 5},
    {"name": "Cucumber", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 7},
    {"name": "Celery", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 10},
    {"name": "Corn Cob", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 3},
    {"name": "Green Beans", "category": "produce", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 5},
    {"name": "Cauliflower", "category": "produce", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 7},
    {"name": "Pumpkin", "category": "produce", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 30},
    {"name": "Snow Peas", "category": "produce", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 4},
    {"name": "Bok Choy", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 4},
    {"name": "Spring Onion", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 7},
    {"name": "Coriander (Fresh)", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 7},
    # --- Produce (Fruit) ---
    {"name": "Lemon", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 21},
    {"name": "Lime", "category": "produce", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 14},
    {"name": "Avocado", "category": "produce", "default_unit": "units", "default_storage": "pantry", "typical_shelf_life_days": 5},
    # --- Dairy ---
    {"name": "Milk", "category": "dairy", "default_unit": "ml", "default_storage": "fridge", "typical_shelf_life_days": 10},
    {"name": "Butter", "category": "dairy", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 30},
    {"name": "Tasty Cheese", "category": "dairy", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 28},
    {"name": "Parmesan", "category": "dairy", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 42},
    {"name": "Mozzarella", "category": "dairy", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 14},
    {"name": "Cream", "category": "dairy", "default_unit": "ml", "default_storage": "fridge", "typical_shelf_life_days": 10},
    {"name": "Sour Cream", "category": "dairy", "default_unit": "ml", "default_storage": "fridge", "typical_shelf_life_days": 14},
    {"name": "Greek Yoghurt", "category": "dairy", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 14},
    {"name": "Eggs", "category": "dairy", "default_unit": "units", "default_storage": "fridge", "typical_shelf_life_days": 35},
    {"name": "Feta", "category": "dairy", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 14},
    {"name": "Haloumi", "category": "dairy", "default_unit": "g", "default_storage": "fridge", "typical_shelf_life_days": 14},
    {"name": "Coconut Cream", "category": "dairy", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 365},
    # --- Pantry ---
    {"name": "Plain Flour", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 180},
    {"name": "Self-Raising Flour", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 180},
    {"name": "Sugar", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": None},
    {"name": "Brown Sugar", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": None},
    {"name": "Diced Tomatoes (Canned)", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 730},
    {"name": "Tomato Paste", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Coconut Milk", "category": "pantry", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Chicken Stock", "category": "pantry", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Beef Stock", "category": "pantry", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Vegetable Stock", "category": "pantry", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Baked Beans (Canned)", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 730},
    {"name": "Chickpeas (Canned)", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 730},
    {"name": "Lentils (Dried)", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Breadcrumbs", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 180},
    {"name": "Peanut Butter", "category": "pantry", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 180},
    {"name": "Honey", "category": "pantry", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": None},
    # --- Grains ---
    {"name": "Jasmine Rice", "category": "grains", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Basmati Rice", "category": "grains", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Arborio Rice", "category": "grains", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Spaghetti", "category": "grains", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 730},
    {"name": "Penne", "category": "grains", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 730},
    {"name": "Egg Noodles", "category": "grains", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Couscous", "category": "grains", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Rolled Oats", "category": "grains", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Bread (Sliced)", "category": "grains", "default_unit": "units", "default_storage": "pantry", "typical_shelf_life_days": 5},
    {"name": "Tortillas", "category": "grains", "default_unit": "units", "default_storage": "pantry", "typical_shelf_life_days": 14},
    # --- Spices ---
    {"name": "Salt", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": None},
    {"name": "Black Pepper", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 730},
    {"name": "Cumin (Ground)", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Paprika", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Smoked Paprika", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Turmeric (Ground)", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Coriander (Ground)", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Chilli Flakes", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Cinnamon (Ground)", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Mixed Herbs", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Garlic Powder", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Onion Powder", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Curry Powder", "category": "spices", "default_unit": "g", "default_storage": "pantry", "typical_shelf_life_days": 365},
    # --- Condiments ---
    {"name": "Olive Oil", "category": "condiments", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Vegetable Oil", "category": "condiments", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Sesame Oil", "category": "condiments", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 365},
    {"name": "Soy Sauce", "category": "condiments", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 730},
    {"name": "Fish Sauce", "category": "condiments", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 730},
    {"name": "Oyster Sauce", "category": "condiments", "default_unit": "ml", "default_storage": "fridge", "typical_shelf_life_days": 365},
    {"name": "Worcestershire Sauce", "category": "condiments", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": 730},
    {"name": "Tomato Sauce (Ketchup)", "category": "condiments", "default_unit": "ml", "default_storage": "fridge", "typical_shelf_life_days": 180},
    {"name": "BBQ Sauce", "category": "condiments", "default_unit": "ml", "default_storage": "fridge", "typical_shelf_life_days": 180},
    {"name": "Sweet Chilli Sauce", "category": "condiments", "default_unit": "ml", "default_storage": "fridge", "typical_shelf_life_days": 180},
    {"name": "Dijon Mustard", "category": "condiments", "default_unit": "ml", "default_storage": "fridge", "typical_shelf_life_days": 365},
    {"name": "Vinegar (White)", "category": "condiments", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": None},
    {"name": "Balsamic Vinegar", "category": "condiments", "default_unit": "ml", "default_storage": "pantry", "typical_shelf_life_days": None},
    {"name": "Sriracha", "category": "condiments", "default_unit": "ml", "default_storage": "fridge", "typical_shelf_life_days": 365},
]
